interface Response {
  question: string;
  all_words: string[];
  good_words: string[];
}

export const animals: Response = {
  question: "select animals",
  all_words: [
    "hole",
    "sofa",
    "pear",
    "tiger",
    "oatmeal",
    "square",
    "nut",
    "cub",
    "shirt",
    "tub",
    "passenger",
    "cow",
    "grace",
    "meadow",
    "tight",
    "grounds",
    "wriggle",
    "title",
    "thigh",
    "piece",
    "practical",
    "medieval",
    "bulb",
    "exotic",
    "fox",
    "authorise",
    "regret",
  ],
  good_words: ["tiger", "cow"],
};

export const colors: Response = {
  question: "select colors",
  all_words: [
    "jeans",
    "existence",
    "ink",
    "red",
    "blue",
    "yellow",
    "laugh",
    "behavior",
    "expansion",
    "white",
    "black",
    "cakes",
    "technique",
    "suffering",
    "pen",
    "physical",
    "information",
    "point",
    "thinker",
    "cast",
    "exceed",
    "aquarium",
    "division",
    "pit",
    "lesson",
    "follow",
    "carbon",
  ],
  good_words: ["red", "blue", "yellow", "white", "black", "carbon"],
};

export const vehicles: Response = {
  question: "select vehicles",
  all_words: [
    "belief",
    "wire",
    "car",
    "bus",
    "star",
    "river",
    "hat",
    "skirt",
    "train",
    "innocent",
    "motorist",
    "debate",
    "function",
    "reflect",
    "preference",
    "provide",
    "eavesdrop",
    "relationship",
    "guerrilla",
    "skate",
    "jacket",
    "meal",
    "appointment",
    "adoption",
  ],
  good_words: ["car", "bus", "train"],
};
